apiVersion: v2
name: trustification
description: A Helm chart for managing Trustification services on Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: keycloak
  version: "=22.2.6"
  repository: "https://charts.bitnami.com/bitnami"
  condition: keycloak.enabled
