[workspace]
members = [
    "api",
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/model",
    "bombastic/indexer",
    "bombastic/index",
    "bombastic/walker",
    "bommer",
    "bommer/bommer-api",
    "vexination/vexination",
    "vexination/api",
    "vexination/index",
    "vexination/model",
    "vexination/indexer",
    "vexination/walker",
    "reservoir/reservoir",
    "reservoir/api",
    "spog/api",
    "spog/model",
    "spog/spog",
    "exhort/api",
    "exhort/exhort",
    "collectorist/api",
    "collectorist/collectorist",
    "integration-tests",
    "trust",
    "exporter",
    "event-bus",
    "storage",
    "index",
    "infrastructure",
    "version",
]
default-members = [
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/model",
    "bombastic/indexer",
    "bombastic/index",
    "bommer",
    "bommer/bommer-api",
    "vexination/vexination",
    "vexination/api",
    "vexination/index",
    "vexination/model",
    "vexination/indexer",
    "vexination/walker",
    "reservoir/reservoir",
    "reservoir/api",
    "spog/api",
    "spog/model",
    "spog/spog",
    "collectorist/api",
    "collectorist/collectorist",
    "trust",
    "exporter",
    "event-bus",
    "storage",
    "index",
    "infrastructure",
    "version",
]

[patch.crates-io]
#sikula = { git = "https://github.com/ctron/sikula", rev = "cea7429f6b690adcdcd1ce2edb2b9e2277834e03" }
#sikula = { path = "../sikula" }

# also check: spog/ui/Cargo.toml
cyclonedx-bom = { git = "https://github.com/lulf/cyclonedx-rust-cargo", branch = "trustification" }
spdx-rs = { git = "https://github.com/lulf/spdx-rs", rev = "f3f1ea9a72e270c8434f8be6ca1d61608b25b813" }
