[workspace]
members = [
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/indexer",
    "bombastic/index",
    "bommer",
    "bommer/bommer-api",
    "vexination/vexination",
    "vexination/api",
    "vexination/index",
    "vexination/indexer",
    "vexination/walker",
    "reservoir/reservoir",
    "reservoir/api",
    "spog/api",
    "spog/model",
    "spog/search",
    "spog/spog",
    "trust",
    "exporter",
    "event-bus",
    "storage",
]

[patch.crates-io]
sikula = { git = "https://github.com/ctron/sikula", rev = "85760a329b852a485fc8b323f7e50e49f88c32a7" }
