[package]
name = "spog-ui-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2"

[dependencies]
anyhow = "1"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["wasmbind"] }
csaf = { version = "0.5.0", default-features = false }
cve = "0.2"
cyclonedx-bom = "0.4"
gloo-events = "0.2"
gloo-net = "0.4.0"
gloo-storage = "0.3.0"
gloo-utils = { version = "0.2.0", features = ["serde"] }
js-sys = "0.3"
log = "0.4"
openidconnect = "3"
packageurl = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
thiserror = "1"
time = { version = "0.3", features = ["formatting", "macros", "wasm-bindgen"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
yew = { version = "0.21", features = ["csr"] }
yew-more-hooks = "0.3.0"
yew-oauth2 = { version = "0.7.0", features = ["router", "openid"] }

bombastic-model = { path = "../../../../bombastic/model" }
exhort-model = { path = "../../../../exhort/model" }
spog-model = { path = "../../../model" }
spog-ui-common = { path = "../common" }
trustification-api = { path = "../../../../api" }
trustification-common = { path = "../../../../common", default-features = false }
trustification-version = { path = "../../../../version" }
v11y-model = { path = "../../../../v11y/model" }
vexination-model = { path = "../../../../vexination/model" }

[dependencies.web-sys]
version = "0.3.61"
features = [
    "DataTransfer",
    "File",
]
