[package]
name = "trustification-event-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.31", features = ["cmake-build"] }
anyhow = "1"
async-trait = "0.1"
aws-sdk-sqs = "0.27.0"
aws-config = "0.55.2"
futures = "0.3"
thiserror = "1.0"
log = "0.4"
clap = { version = "4", features = ["derive"] }
