[package]
name = "bombastic-event-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.25", features = ["cmake-build"], optional = true }
anyhow = "1"
async-trait = "0.1"
aws-sdk-sqs = { version = "0.27.0", optional = true }
aws-config = { version = "0.55.2", optional = true }
futures = "0.3"
thiserror = "1.0"

[features]
default = ["kafka", "sqs"]
kafka = ["rdkafka"]
sqs = ["aws-sdk-sqs", "aws-config"]
