[package]
name = "trustification-common-walker"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Common tools for walkers"

[dependencies]
anyhow = "1"
async-trait = "0.1"
log = "0.4"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
time = { version = "0.3", features = ["serde-well-known"] }
walker-common = "=0.6.0-rc.1"
walker-extras = "=0.6.0-rc.1"
tera = "1.19.1"
sequoia-openpgp = { version = "*", default-features = false }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

# Enables a crypto backend for the tests:
[target.'cfg(not(windows))'.dev-dependencies]
sequoia-openpgp = { version = "1", default-features = false, features = ["crypto-nettle", "__implicit-crypto-backend-for-tests"]  }

# Enables a crypto backend for the docs.rs generation:
[package.metadata.docs.rs]
features = ["sequoia-openpgp/default"]
