{{- if .Values.modules.spogApi.enabled }}
{{- $mod := dict "root" . "name" "spog-api" "component" "spog" "module" .Values.modules.spogApi -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
    {{- include "trustification.application.annotations" $mod | nindent 4 }}

spec:
  replicas: {{ include "trustification.application.replicas" $mod }}
  selector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustification.common.selectorLabels" $mod | nindent 8 }}
        {{- include "trustification.application.podLabels" $mod | nindent 8 }}
      annotations:
        configHash/auth: {{ include (print $.Template.BasePath "/services/spog/api/020-ConfigMap-auth.yaml") . | sha256sum }}
        configHash/ui: {{ include (print $.Template.BasePath "/services/spog/api/020-ConfigMap-ui.yaml") . | sha256sum }}

    spec:
      {{- include "trustification.application.pod" $mod | nindent 6 }}

      containers:
        - name: service
          {{ include "trustification.common.defaultImage" $mod | nindent 10 }}
          command: ["/trust"]
          args:
            - "spog"
            - "api"
            - "-p"
            - "8080"
            - "--bombastic-url"
            - "http://bombastic-api.$(NAMESPACE).svc"
            - "--vexination-url"
            - "http://vexination-api.$(NAMESPACE).svc"
            - "--collectorist-url"
            - "http://collectorist-api.$(NAMESPACE).svc"
            - "--v11y-url"
            - "http://v11y-api.$(NAMESPACE).svc"
            - "--exhort-url"
            - "http://exhort-api.$(NAMESPACE).svc"
{{- with $mod.crdaUrl }}
            - "--crda-url"
            - {{ . | quote }}
{{- end }}
            - "--guac"
            - "http://guac-graphql.$(NAMESPACE).svc:8080/query"
            - "--auth-configuration"
            - "/etc/config/auth.yaml"
          env:

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            {{- include "trustification.application.rust.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.infrastructure.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.httpServer.envVars" $mod | nindent 12 }}
            {{- include "trustification.oidc.authenticationClient" ( dict "root" . "clientId" "walker" ) | nindent 12 }}

            {{- with $mod.snykToken }}
            - name: SNYK_TOKEN
              {{- include "trustification.common.envVarValue" . | nindent 14 }}
            {{- end }}

            {{- with $mod.segmentWriteKey }}
            - name: SEGMENT_WRITE_KEY
              {{- include "trustification.common.envVarValue" . | nindent 14 }}
            {{- end }}

            {{- if not $mod.disableSwaggerOidc }}
            - name: SWAGGER_UI_OIDC_ISSUER_URL
              value: {{ include "trustification.oidc.frontendIssuerUrl" . | quote }}
            {{- end }}

            {{- if $mod.uiConfiguration }}
            - name: SPOG_UI_CONFIG
              value: /etc/config/spog-ui/spog-ui.yaml
            {{- end }}

          ports:
            {{- include "trustification.application.infrastructure.podPorts" $mod | nindent 12 }}
            - containerPort: 8080
              name: endpoint
              protocol: TCP

          {{- include "trustification.application.container" $mod | nindent 10 }}
          {{- include "trustification.application.infrastructure.probes" $mod | nindent 10 }}

          volumeMounts:
            {{- include "trustification.application.httpServerVolumesMounts" $mod | nindent 12 }}
            {{- include "trustification.authenticator.volumeMount" $mod | nindent 12 }}

            {{- if $mod.uiConfiguration }}
            - name: config-ui
              mountPath: /etc/config/spog-ui.yaml
              subPath: {{ if ($mod.uiConfiguration.configMapRef).key }}{{ $mod.uiConfiguration.configMapRef.key }}{{ else }}spog-ui.yaml{{ end }}
            {{- end }}

      volumes:
        {{- include "trustification.application.httpServerVolumes" $mod | nindent 8 }}
        {{- include "trustification.authenticator.volume" $mod | nindent 8 }}

        {{- if $mod.uiConfiguration }}
        - name: config-ui
          configMap:
            name: {{ with $mod.uiConfiguration.configMapRef }}{{ .name }}{{ else }}{{ .Release.Name }}-spog-ui-config{{ end }}
        {{- end }}

{{ end }}
