[package]
name = "exhort-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
guac = { workspace = true }
### this seems completely wrong, but Cargo seems to also require way too many ../ for this
### wtf am I doing wrong?
collectorist-client = { path = " ../../../../collectorist/client" }
exhort-model = { path = "../model" }
v11y-client = { path = "../../v11y/client"}
trustification-common = { path = "../../common"}
trustification-infrastructure = { path = "../../infrastructure" }
trustification-auth = { path = "../../auth" }
reqwest = "0.11.18"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
thiserror = "1.0.44"
utoipa = { version = "3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68", features = [ "raw_value" ] }
packageurl = "0.3"

[dev-dependencies]
env_logger = "0.10"

[build-dependencies]
tonic-build = "0.9.2"
