[package]
name = "spog-model"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

description = "The data model of the API"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
csaf = { version = "0.5.0", default-features = false }
schemars = { version = "0.8", features = ["url"] }
serde = { version = "1", features = ["derive"] }
time = { version = "0.3" }
url = { version = "2", features = ["serde"] }
utoipa = { version = "4", features = ["url"] }
cvss = "2"

exhort-model = { path = "../../exhort/model" }
vexination-model = { path = "../../vexination/model" }
v11y-model = { path = "../../v11y/model" }

# required by ToSchema utopia
serde_json = "1"
urlencoding = "2"

[dev-dependencies]
serde_json = "1"
anyhow = "1"