[package]
name = "collector-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reqwest = { version = "0.12.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
url = "2"

trustification-auth = { path = "../../auth" }



