[package]
name = "vexination-walker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
trustification-storage = { path = "../../storage" }
trustification-infrastructure = { path = "../../infrastructure" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
sha2 = "0.10"
hex = "0.4.3"
packageurl = "0.3"
rand = "0.8"
csaf = "0.5.0"
csaf-walker = { version = "0.3", default-features = false, features = ["crypto-openssl"] }
url = { version = "2.3.1", features = ["serde"] }
time = "0.3.21"
humantime = "2.1.0"
prometheus = "0.13.3"
