parameters:
- name: BACKEND_IMAGE
  required: true
- name: FRONTEND_IMAGE
  required: true
- name: INTEGRATION_TESTS_IMAGE
  required: true
- name: IMAGE_TAG
  required: true
- name: AWS_REGION
  required: true
- name: BOMBASTIC_STORAGE_BUCKET
  required: true
- name: BOMBASTIC_AWS_SECRET_NAME
  required: true
- name: BOMBASTIC_INDEXER_STORED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_INDEXED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_FAILED_TOPIC
  required: true
- name: BOMBASTIC_INDEXER_GUAC_TOPIC
  required: true
- name: BOMBASTIC_WALKER_RESOURCES
  required: true
- name: VEXINATION_STORAGE_BUCKET
  required: true
- name: VEXINATION_AWS_SECRET_NAME
  required: true
- name: VEXINATION_INDEXER_STORED_TOPIC
  required: true
- name: VEXINATION_INDEXER_INDEXED_TOPIC
  required: true
- name: VEXINATION_INDEXER_FAILED_TOPIC
  required: true
- name: VEXINATION_INDEXER_GUAC_TOPIC
  required: true
- name: ISSUER_URL
  required: true
- name: CONFIG_NAME
  required: true
- name: DOMAIN
  required: true
- name: BOMBASTIC_INDEXER_RESOURCES
  required: true
- name: BOMBASTIC_API_RESOURCES
  required: true
- name: VEXINATION_API_RESOURCES
  required: true
- name: VEXINATION_INDEXER_RESOURCES
  required: true
- name: V11Y_INDEXER_RESOURCES
  required: true
- name: V11Y_WALKER_RESOURCES
  required: true
- name: SPOG_API_RESOURCES
  required: true
- name: SPOG_UI_RESOURCES
  required: true
- name: OIDC_PROVIDER_CLIENT_SECRET_NAME
  required: true
- name: OIDC_PROVIDER_CLIENT_SECRET_KEY
  required: true
- name: V11Y_API_RESOURCES
  required: true
- name: V11Y_STORAGE_BUCKET
  required: true
- name: V11Y_AWS_SECRET_NAME
  required: true
- name: V11Y_INDEXER_STORED_TOPIC
  required: true
- name: V11Y_INDEXER_INDEXED_TOPIC
  required: true
- name: V11Y_INDEXER_FAILED_TOPIC
  required: true
- name: V11Y_INDEXER_GUAC_TOPIC
  required: true
- name: COLLECTORIST_RESOURCES
  required: true
- name: COLLECTOR_OSV_RESOURCES
  required: true
- name: COLLECTOR_SNYK_RESOURCES
  required: true
- name: EXHORT_API_RESOURCES
  required: true
- name: GUAC_IMAGE
  required: true
- name: GUAC_GQL_RESOURCES
  required: true
- name: GUAC_GQL_AFFINITY
  value: "{}"
- name: GUAC_GRAPHQL_REPLICAS
  required: true
- name: GUAC_COLLECTSUB_REPLICAS
  required: true
- name: BOMBASTIC_API_REPLICAS
  required: true
- name: BOMBASTIC_INDEXER_REPLICAS
  required: true
- name: COLLECTORIST_API_REPLICAS
  required: true
- name: COLLECTOR_OSV_REPLICAS
  required: true
- name: EXHORT_API_REPLICAS
  required: true
- name: SPOG_API_REPLICAS
  required: true
- name: SPOG_UI_REPLICAS
  required: true
- name: VEXINATION_API_REPLICAS
  required: true
- name: VEXINATION_INDEXER_REPLICAS
  required: true
- name: V11Y_API_REPLICAS
  required: true
- name: V11Y_INDEXER_REPLICAS
  required: true
- name: BOMBASTIC_COLLECTOR_RESOURCES
  required: true
- name: VEXINATION_COLLECTOR_RESOURCES
  required: true
- name: K8S_NAMESPACE
  required: true
- name: VEXINATION_WALKER_SCHEDULE
  value: "10 * * * *"
- name: BOMBASTIC_WALKER_SCHEDULE
  value: "10 * * * *"
- name: V11Y_WALKER_SCHEDULE
  value: "1 0 * * *"
- name: VEXINATION_COLLECTOR_SCHEDULE
  value: "30 * * * *"
- name: BOMBASTIC_COLLECTOR_SCHEDULE
  value: "0 * * * *"
- name: V11Y_API_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: V11Y_INDEXER_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: V11Y_INDEXER_INDEX_WRITER_MEMORY_BYTES
  value: "134217728"
- name: BOMBASTIC_API_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: BOMBASTIC_INDEXER_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: BOMBASTIC_INDEXER_INDEX_WRITER_MEMORY_BYTES
  value: "134217728"
- name: VEXINATION_API_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: VEXINATION_INDEXER_INDEX_SYNC_INTERVAL
  value: "1800s"
- name: VEXINATION_INDEXER_INDEX_WRITER_MEMORY_BYTES
  value: "134217728"
- name: LOG_LEVEL
  required: false
  value: "info"
- name: CRDA_URL
  required: false
  value: https://rhda.rhcloud.com/api/v4/analysis
- name: BOMBASTIC_WALKER_SUSPEND
  value: "false"
- name: V11Y_WALKER_SUSPEND
  value: "false"
- name: VEXINATION_WALKER_SUSPEND
  value: "false"
- name: SEGMENT_SECRET_NAME
  value: segment-write-keys
- name: SEGMENT_SECRET_API_KEY
  value: spogApi
- name: SEGMENT_SECRET_UI_KEY
  value: spogUi
- name: POSTGRESQL_IMAGE
  value: "docker.io/library/postgres:15"
- name: GUAC_INIT_JOB_SERVICE_ACCOUNT
  value: trustification-service
- name: INITIAL_BACKEND_JSON
  value: "{}"
- name: DATASET_ENABLED_JOB
  value: "true"
- name: DATASET_SUSPEND_JOB
  value: "true"
- name: DATASET_SCHEDULE_JOB
  value: "0 * * * *"
- name: REPLICAS
  value: "1"
