[package]
name = "v11y-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
reqwest = "0.11.18"
anyhow = "1"
v11y-model = { path = "../model" }
thiserror = "1.0.44"

trustification-api = { path = "../../api" }
trustification-auth = { path = "../../auth" }
trustification-infrastructure = { path = "../../infrastructure" }

[dev-dependencies]
tokio = "1"



