[package]
name = "exhort-model"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
packageurl = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["raw_value"] }
utoipa = "4"



v11y-model = { path = "../../v11y/model" }