on:
  pull_request_target:
    branches:
      - main
      - stable
      - release/*
    types:
      - closed

env:
  USERNAME: "@trustification-bot:matrix.org"
  PASSWORD: ${{ secrets.MATRIX_BOT_PASSWORD }}
  ROOM: "#trustification:matrix.org"

jobs:
  notify_channel:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
      - name: Send message
        run: |
          podman run --rm docker.io/matrixcommander/matrix-commander:latest --login password --homeserver https://matrix.org --device github --user-login "$USERNAME" --password "$PASSWORD" --room-default "$ROOM" --message "ðŸŽ‰ PR merged: ${{ github.event.pull_request.html_url }}"  --logout me
